  name: flask_hw
  on:
    push:
      branches:
        - heroku_hw
  jobs:
    tests:
      runs-on: ubuntu-latest

      services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres
          # Provide the password for postgres
          env:
            POSTGRES_PASSWORD: postgres
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements-d.txt

        - name: Test with pytest
          env:
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
          run: pytest

    deploy:
      needs: tests

      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "mexalon-flask-hw"
            heroku_email: "nabarysh@gmail.com"
            usedocker: true